all:
  client: &client
    all: [read, create, edit, delete]
    owner: [read, create, edit, delete]
  coupon:
    all: [read, create, edit, delete]
  invoice:
    all: [read, create, edit, delete, disable]
    owner: [read, create, edit, delete, disable]
  product: 
    all: [read, create, edit, delete]
  user:
    all: [read, create, edit, delete]
    owner: [read, create, edit, delete]