default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: db
  database: sgc_development
  username: postgres
  password: postgres

test:
  <<: *default
  host: db
  database: sgc_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: sgc_production
  username: sgc
  password: <%= ENV['SGC_DATABASE_PASSWORD'] %>
